{% set name = "napari-h5" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-h5-{{ version }}.tar.gz
  sha256: de75fa4b794ba8310364d03bd627a443a4931e7acc5be278e74aaf76e5a2e122

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
  run:
    - dask-core
    - h5py
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_h5
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-h5
  summary: A hdf5 file reader plugin for napari
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/rosalindfranklininstitute/napari-h5

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
